# Generated by Django 2.2.12 on 2020-05-10 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0002_auto_20200510_0147"),
    ]

    operations = [
        migrations.RenameField(
            model_name="invoiceitem", old_name="title", new_name="description",
        ),
    ]
