# Generated by Django 2.2.12 on 2020-06-10 19:38

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0006_auto_20200610_0320"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=8,
                validators=[django.core.validators.MinValueValidator(Decimal("0.1"))],
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="hours",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=3,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.1"))],
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=6,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.1"))],
            ),
        ),
    ]
