# Generated by Django 2.2.12 on 2020-05-10 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
