# Generated by Django 2.2.12 on 2020-06-09 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0003_auto_20200510_2052"),
    ]

    operations = [
        migrations.RenameField(
            model_name="partner", old_name="guid", new_name="partner_id",
        ),
    ]
