# Generated by Django 2.2.12 on 2020-07-20 23:48

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200715_0405'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='address1',
            field=models.CharField(default='N/A', help_text='Street address, P.O. box', max_length=48),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='address2',
            field=models.CharField(blank=True, help_text='Apartment, suite, unit, building, floor', max_length=32),
        ),
        migrations.AddField(
            model_name='account',
            name='city',
            field=models.CharField(default='N/A', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='account',
            name='state',
            field=models.CharField(default='N/A', help_text='Should use 2 letter abbreviations for U.S. states', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='zipcode',
            field=models.CharField(default='N/A', max_length=16),
            preserve_default=False,
        ),
    ]
